site_name: PALM
docs_dir: docs
nav:
  - Home: PALM.md
  - User Guide: User guide.md
  - Exchangeability Blocks: Exchangeability blocks.md
  - Joint Inference: Joint inference.md
  - Masks and Voxelwise Regressors: Masks and voxelwise regressors.md
  - Faster Inference: Faster inference.md
  - Viewing Results: Viewing results.md
  - Examples: Examples.md
  - Frequently Asked Questions: Frequently asked questions.md

