site_name: PALM
site_description: Documentation for PALM (Permutation Analysis of Linear Models) - FSL
site_url: https://fsl.fmrib.ox.ac.uk/fsl/docs/
repo_url: https://github.com/andersonwinkler/PALM
repo_name: andersonwinkler/PALM

docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: grey
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - awesome-pages  # Optional, for better navigation control

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js

extra_css:
  - https://assets.readthedocs.org/static/css/badge_only.css
  - https://assets.readthedocs.org/static/css/readthedocs-doc-embed.css
  - css/custom.css

nav:
  - Home: PALM.md
  - User Guide: User guide.md
  - Exchangeability Blocks: Exchangeability blocks.md
  - Joint Inference: Joint inference.md
  - Masks and Voxelwise Regressors: Masks and voxelwise regressors.md
  - Faster Inference: Faster inference.md
  - Viewing Results: Viewing results.md
  - Examples: Examples.md
  - Frequently Asked Questions: Frequently asked questions.md

