function [G,df2] = palm_fastt(M,psi,res,plm)
% This function is a simplification of 'pivotal.m',
% without argument checking and that works only if:
% - rank(contrast) = 1
% - number of variance groups = 1
% 
% Inputs:
% M   : design matrix
% psi : regression coefficients
% res : residuals
% plm : a struct with many things as generated by
%       'palm.m' and 'takeargs.m'
% 
% Outputs:
% G   : In this particular case, G is the t statistic.
% df2 : Degrees of freedom. df1 = 1 for the t statistic.
%
% For the full explanation, see the generic, but much
% slower 'pivotal.m'
%  
% _____________________________________
% Anderson Winkler and Tom Nichols
% FMRIB / University of Oxford
% Aug/2013
% http://brainder.org

df2 = plm.tmp.N-plm.tmp.rM;
G = plm.tmp.eC'*psi;
den = sqrt(plm.tmp.eC'*inv(M'*M)*plm.tmp.eC*sum(res.^2)./df2); %#ok inv here
G = G./den;
