#!/bin/bash
# This is a wrapper to call PALM in Octave or Matlab, depending
# on the user's preferences and what is available in the system.
# _____________________________________
# Anderson M. Winkler
# FMRIB / Univ. of Oxford
# Mar/2014
# http://brainder.org

# =========================================================================
# Do you prefer Matlab or Octave? Octave is free (it doesn't need licences),
# is faster to load, but somewhat slower to run. Matlab uses licenses (this
# may bother other users in a network), is slower to load, but runs faster
# once loaded. In the var below, use 1 for Octave, 2 for Matlab:
WHICH_TO_RUN=1

# If Octave isn't in the path, or to use a specific version,
# add here the path to the Octave executable binary:
OCTAVEPATH=/usr/bin

# If Matlab isn't in the path, or to use a specific version,
# add here the path to the Matlab executable binary:
#MATLABPATH=/Applications/MATLAB_R2013b.app/bin/
#MATLABPATH=/opt/11b/bin/
MATLABPATH=/usr/local/bin/

# =========================================================================
# Normally there is no need to edit below this line:

# Locate PALM
cmdfull=${BASH_SOURCE[0]}
PALMDIR=$(dirname ${cmdfull})
rlink=$(readlink ${cmdfull})
cnt=1
while [[ ${rlink} != "" ]] && [[ ${cnt} -lt 100 ]]; do
  dirnam=$(dirname ${rlink})
  if [[ ${dirnam:0} == "/" ]] ; then
    PALMDIR=${dirnam}
  else
    PALMDIR="${PALMDIR}/${dirnam}"
  fi
  rlink=$(readlink ${rlink})
  cnt=$(expr ${cnt} + 1)
done
if [[ ${cnt} -eq 100 ]] ; then
  echo "Error: Too many levels."
  exit 1
fi

# Command to run inside either Octave or Matlab
RUNCMD="addpath('$PALMDIR'); palm $@ ; exit" 

# Call either Octave or Matlab depending on the user's choice
if [[ ${WHICH_TO_RUN} -eq 1 ]] ; then
   if [[ ${OCTAVEPATH} == "" ]] ; then
      OCTAVECMD=octave
   else
      OCTAVECMD=${OCTAVEPATH}/octave
   fi
   ${OCTAVECMD} -q --eval "${RUNCMD}"
elif [[ ${WHICH_TO_RUN} -eq 2 ]] ; then
   if [[ ${MATLABPATH} == "" ]] ; then
      MATLABCMD=matlab
   else
      MATLABCMD=${MATLABPATH}/matlab
   fi
   ${MATLABCMD} -nodesktop -nojvm -nosplash -singleCompThread -r "${RUNCMD}" \
     | sed -e '1,/^.......................................................................$/ d'
fi

# That's it!
