function [G,df2] = palm_fastv(M,psi,res,plm)
% This function is a simplification of 'pivotal.m',
% without argument checking and that works only if:
% - rank(contrast) = 1
% - number of variance groups > 1
% 
% Inputs:
% M   : design matrix
% psi : regression coefficients
% res : residuals
% plm : a struct with many things as generated by
%       'palm.m' and 'takeargs.m'
% 
% Outputs:
% G   : In this particular case, G is the Aspin-Welch
%       v statistic (for the well known Behrens-Fisher
%       problem).
% df2 : Degrees of freedom 2. df1 is 1.
%
% For the full explanation, see the generic, but much
% slower 'pivotal.m'
%  
% _____________________________________
% Anderson Winkler and Tom Nichols
% FMRIB / University of Oxford
% Aug/2013
% http://brainder.org

r = size(M,2);
m = size(res,2);
[~,~,blkidx] = unique(plm.tmp.VG);

W = zeros(plm.tmp.nVG,m);
dRmb = zeros(plm.tmp.nVG,1);
cte = zeros(r^2,m);
for b = 1:plm.tmp.nVG,
    bidx = blkidx == b;
    dRmb(b) = sum(plm.tmp.dRm(bidx));
    W(b,:) = dRmb(b)./sum(res(bidx,:).^2);
    Mb = M(bidx,:)'*M(bidx,:);
    cte = cte + Mb(:)*W(b,:);
    W(b,:) = W(b,:)*sum(bidx);
end

den = zeros(1,m);
for t = 1:m,
    den(t) = plm.tmp.eC'*inv(reshape(cte(:,t),[r r]))*plm.tmp.eC; %#ok inv here
end
G = plm.tmp.eC'*psi./sqrt(den);

bsum = zeros(1,m);
sW1 = sum(W,1);
for b = 1:plm.tmp.nVG,
    bsum = bsum + bsxfun(@rdivide,(1-W(b,:)./sW1).^2,dRmb(b));
end
df2 = 1/3./bsum;
