#!/bin/bash
# This is a wrapper to call PALM in Octave or Matlab, depending
# on the user's preferences and what is available in the system.
# _____________________________________
# Anderson M. Winkler
# FMRIB / Univ. of Oxford
# Mar/2014
# http://brainder.org

# =========================================================================
# Do you prefer Matlab or Octave? Octave is free (it doesn't need licences),
# is faster to load, but somewhat slower to run. Matlab uses licenses (this
# may bother other users in a network), is slower to load, but runs faster
# once loaded. In the var below, use 0 for Matlab, 1 for Octave:
WHICH_TO_RUN=0

# If Octave isn't in the path, or to use a specific version,
# add here the path to the Octave executable binary:
OCTAVEPATH=""

# If Matlab isn't in the path, or to use a specific version,
# add here the path to the Matlab executable binary:
#MATLABPATH="/Applications/MATLAB_R2013b.app/bin/"
MATLABPATH=/opt/11b/MATLAB_R2011b.app/bin/

# =========================================================================
# Normally there is no need to edit below this line:

# Locate PALM
PALMDIR=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)

# Call either Octave or Matlab depending on the user's choice
if [[ ${WHICH_TO_RUN} -eq 1 ]] ; then
   if [[ ${OCTAVEPATH} == "" ]] ; then
      OCTAVECMD=octave
   else
      OCTAVECMD=${OCTAVEPATH}/octave
   fi
   ${OCTAVECMD} -q --eval "addpath('$PALMDIR'); palm $@ ; exit"
elif [[ ${WHICH_TO_RUN} -eq 0 ]] ; then
   if [[ ${MATLABPATH} == "" ]] ; then
      MATLABCMD=matlab
   else
      MATLABCMD=${MATLABPATH}/matlab
   fi
   echo ${MATLABCMD} -nodesktop -nojvm -nosplash -singleCompThread \
             -r "addpath('$PALMDIR'); palm $@ ; exit" 
            # sed -e '1,/^.......................................................................$/ d'
fi

# That's it!
