#!/usr/bin/awk -f

BEGIN { if (ARGV[1] == "") { 
print "Transpose a CSV file, such that lines become columns"
print "and columns become lines."
print ""
print "Example usage:"
print "mat2det origfile.csv > transpfile.csv"
print ""
print "_____________________________________"
print "Anderson M. Winkler"
print "Yale University / Institute of Living"
print "Jan/2011"
print "http://brainder.org."
exit } }

{ FS=OFS="," }
{ for (i = 1; i <= NF; i++) { a[i,NR] = $i }; m = NF; n = NR }
END {
for ( j = 1; j <= m; j++ )
  for ( k = 1; k <= n ; k++)
    printf( "%s%s", a[j,k], ( k == n ) ? "\n" : OFS )
}

